# set the name of the app
name: baseapp
description: A Base Flutter App for DevYahia Projects.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter        
  intl: ^0.17.0
  # icons
  cupertino_icons: ^1.0.4
  # state management & DI
  provider: ^6.0.0
  # code generation
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # icons & stuff
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  # code generation
  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.1

# run this command in terminal to activate -> flutter pub run flutter_launcher_icons:main
# visit https://pub.dev/packages/flutter_launcher_icons for more parameters
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# run this command in terminal to activate -> flutter pub run flutter_native_splash:create
# visit https://pub.dev/packages/flutter_native_splash for more parameters
flutter_native_splash:
  color: "#42a5f5"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
